name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      # ------------------------------------------
      # 1. Build Docker Image
      # ------------------------------------------
      - name: Build Docker Image
        run: |
          docker build -t adservice:latest -f src/adservice/Dockerfile src/adservice
      # ------------------------------------------
      # 2. Trivy Vulnerability Scan (HTML Report)
      # ------------------------------------------
      - name: Run Trivy Scan (HTML)
        run: |
          mkdir -p trivy-report
          trivy image --format template \
            --template "@contrib/html.tpl" \
            -o trivy-report/scan.html \
             adservice:latest
      # ------------------------------------------
      # 3. Upload HTML Report Artifact
      # ------------------------------------------
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-html-report
          path: trivy-report/scan.html
          retention-days: 30
