name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: label-1

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build \
            -t my-image-name:${{ github.run_number }} \
            -f src/adservice/Dockerfile \
            src/adservice

